#!/usr/bin/env python3
#filter out extremely minor crimes
select_crimes = [
        'THEFT - PETTY',
        'Disturbance of the Peace',
        'Assault w/Deadly Wepaon Just Occurred',
        'Grand Theft Auto Report',
        'Trespassing',
        'Fight',
        'Disturbance of the Peace Report',
        'Burglary Investigation/Walk Through',
        'THEFT - GRAND',
        'Person with a Gun',
        'Sexual Assault',
        'Burglary Report',
        'Petty Theft Report',
        'Grand Theft Report',
        'VANDALISM',
        'THEFT - PETTY (FROM VEHICLE)',
        'INTIMATE PARTNER - SIMPLE ASSAULT',
        'DISCHARGE FIREARMS/SHOTS FIRED',
        'VANDALISM - MISDEAMEANOR ($399 OR UNDER)',
        'BURGLARY',
        'INTIMATE PARTNER - AGGRAVATED ASSAULT',
        'SHOPLIFTING - PETTY THEFT ($950 & UNDER)',
        'BURGLARY FROM VEHICLE',        
        'VEHICLE - STOLEN' 'VIOLATION OF COURT ORDER',
        'THEFT PLAIN - PETTY ($950 & UNDER)',
        'ROBBERY',
        'THEFT FROM MOTOR VEHICLE - PETTY ($950 & UNDER)',
        'THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LIVESTK,PROD',
        'BATTERY - SIMPLE ASSAULT',
        'ATTEMPTED ROBBERY',
        'VANDALISM - FELONY ($400 & OVER, ALL CHURCH VANDALISMS)',
        'ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT',
        'CHILD ABUSE (PHYSICAL) - SIMPLE ASSAULT',
        'BURGLARY - FROM A MOTOR VEHICLE',
        'BURGLARY, ATTEMPTED',
        'THEFT FROM MOTOR VEHICLE - GRAND ($400 AND OVER)',
        'RAPE, FORCIBLE',
        'VEHICLE - ATTEMPT STOLEN',
        'VIOLATION OF RESTRAINING ORDER',
        'BRANDISH WEAPON' 'TRESPASSING',
        'PURSE SNATCHING - ATTEMPT',
        'THEFT, PERSON',
        'Domestic Violence Just Occurred',
        'BIKE - STOLEN',
        'ASSAULT - SIMPLE',
        'Drunk Driving Investigation',
        'BUNCO, GRAND THEFT',
        'BURGLARY - COMMERCIAL BUILDING',
        'SEXUAL PENETRATION W/FOREIGN OBJECT',
        'Panhandling',
        'Strongarm Robbery Just Occurred',
        'EMBEZZLEMENT, GRAND THEFT ($950.01 & OVER)',
        'RAPE, ATTEMPTED',
        'Urinating/Defecating in Public',
        'DISTURBING THE PEACE',
        'Assault Just Occurred',
        'OTHER ASSAULT',
        'CHILD NEGLECT (SEE 300 W.I.C.)',
        'ARSON',
        'CHILD STEALING',
        'SEX,UNLAWFUL(INC MUTUAL CONSENT, PENETRATION W/ FRGN OBJ',
        'EXTORTION',
        'BUNCO, PETTY THEFT',
        'OTHER MISCELLANEOUS CRIME',
        'SHOPLIFTING-GRAND THEFT ($950.01 & OVER)',
        'SHOTS FIRED AT MOVING VEHICLE, TRAIN OR AIRCRAFT',
        'Auto Burglary Now',
        'Hit and Run Felony Investigation',
        'KIDNAPPING - GRAND ATTEMPT',
        'Grand Theft Now',
        'Rape Just Occurred',
        'Armed Robbery Just Occurred',
        'Arson',
        'Illegal Weapon',
        'DUI ARREST',
        'BURGLARY FROM VEHICLE, ATTEMPTED',
        'THEFT - GRAND (FROM VEHICLE)',
        'BURGLARY - RESIDENTIAL (NO ONE HOME)',
        'THEFT PLAIN - ATTEMPT',
        'BATTERY WITH SEXUAL CONTACT',
        'ASSAULT - AGGRAVATED',
        'Armed Robbery Report',
        'THEFT FROM MOTOR VEHICLE - ATTEMPT',
        'Assault w/Deadly Weapon Report',
        'BATTERY POLICE (SIMPLE)',
        'Attempt Burglary Report',
        'ASSAULT WITH DEADLY WEAPON ON POLICE OFFICER',
        'PICKPOCKET',
        'SHOTS FIRED AT INHABITED DWELLING',
        'KIDNAPPING',
        'Battery Now',
        'HUMAN TRAFFICKING - COMMERCIAL SEX ACTS',
        'SODOMY/SEXUAL CONTACT B/W PENIS OF ONE PERS TO ANUS OTH',
        'Report of Shots Fired',
        'Grand Theft Just Occurred',
        'INDECENT EXPOSURE',
        'Attempt Armed Robbery Just Occurred',
        'SHOPLIFT ROBBERY',
        'Child Endangerment',
        'LEWD CONDUCT',
        'Burglary Now',
        'Domestic Violence Report',
        'BUNCO, ATTEMPT',
        'CRM AGNST CHLD (13 OR UNDER) (14-15 & SUSP 10 YRS OLDER)',
        'Attempt Auto Theft Report',
        'Violation of Restraining Order Report',
        'Grand Theft Auto Just Occurred',
        'Elder Abuse',
        'CRIMINAL HOMICIDE',
        'Indecent Exposure Just Occurred',
        'MOTOR VEHICLE THEFT',
        'Child Abuse',
        'Burglary Just Occurred',
        'CHILD ABUSE (PHYSICAL) - AGGRAVATED ASSAULT',
        'Strongarm Robbery Report',
        'Attempt Burglary Just Occurred',
        'Rape Report',
        'PURSE SNATCHING',
        'STALKING',
        'BURGLARY - CONSTRUCTION SITE',
        'LOJACK Hit',
        'Wanted Vehicle',
        'RECKLESS DRIVING',
        'Stolen Vehicle',
        'BURGLARY - RESIDENTIAL (COMMON AREA)',
        'CHILD ABANDONMENT',
        'Armed Robbery In Progress',
        'WEAPONS POSSESSION/BOMBING',
        'BATTERY ON A FIREFIGHTER',
        'SHOPLIFTING - ATTEMPT',
        'Violation of Restraining Order In Progress',
        'CREDIT CARDS, FRAUD USE ($950.01 & OVER)',
        'CHILD PORNOGRAPHY',
        'BOMB SCARE',
        'Assault Now',
        'THEFT FROM PERSON - ATTEMPT',
        'CRUELTY TO ANIMALS',
        'LYNCHING',
        'LEWD/LASCIVIOUS ACTS WITH CHILD',
        'Auto Burglary Just Occurred',
        'BOAT - STOLEN',
        'Attempt Auto Theft Just Occurred',
        'Strongarm Robbery Now',
        'Attempt Strongarm Robbery Just Occurred',
        'Assault w/Deadly Wepaon Now',
        'Attempt Strongarm Robbery Report',
        'BURGLARY - RESIDENTIAL (HOME OCCUPIED)',
        'DISHONEST EMPLOYEE - GRAND THEFT',
        'Assault Report' 'Prostitution',
        'Indecent Exposure Report',
        'Counterfeit Suspect There Now',
        'Child Molestation',
        'PICKPOCKET, ATTEMPT',
        'DRUGS, TO A MINOR',
        'BURGLARY - RESIDENTIAL (ACCESSED GARAGE ONLY)',
        'TILL TAP - GRAND THEFT ($950.01 & OVER)',
        'Stalking Suspect Just Left',
        'Grand Theft Auto In Progress',
        'Receiving Stolen Property Report',
        'HUMAN TRAFFICKING - INVOLUNTARY SERVITUDE',
        'TILL TAP - PETTY ($950 & UNDER)',
        'GRAND THEFT / INSURANCE FRAUD',
        'DISHONEST EMPLOYEE ATTEMPTED THEFT',
        'Kidnap Report',
        'LYNCHING - ATTEMPTED',
        'Child Stealing',
        'Kidnap Just Occurred',
        'INCITING A RIOT',
        'THEFT, COIN MACHINE - GRAND ($950.01 & OVER)',
        'BEASTIALITY, CRIME AGAINST NATURE SEXUAL ASSLT WITH ANIM',
        'Armed Robbery/Auto Theft Report',
        'GRAND THEFT / AUTO REPAIR',
        'FIREARMS TEMPORARY RESTRAINING ORDER (TEMP FIREARMS RO)',
        'ASSAULTS (PRIOR TO SEPT 2018)',
        'GRAND THEFT AUTO',
        'LARCENY THEFT',
        'NON-AGGRAVATED ASSAULTS',
        'NARCOTICS',
        'MISDEMEANORS MISCELLANEOUS',
        'PERSONS MISSING',
        'SEX OFFENSES FELONIES',
        'DRUNK / ALCOHOL / DRUGS',
        'OFFENSES AGAINST FAMILY',
        'DRUNK DRIVING VEHICLE / BOAT' 'WEAPON LAWS',
        'AGGRAVATED ASSAULT',
        'FRAUD AND NSF CHECKS',
        'PERSONS DEAD',
        'Bomb Threat',
        'SEX OFFENSES MISDEMEANORS',
        'SUICIDE AND ATTEMPT',
        'FELONIES MISCELLANEOUS',
        'FORCIBLE RAPE',
        'INCEST (SEXUAL ACTS BETWEEN BLOOD RELATIVES)',
        'Kidnap In Progress',
        'MANSLAUGHTER, NEGLIGENT',
        'Attempt Armed Robbery Report',
        'FAILURE TO DISPERSE',
        'Armed Robbery/Auto Theft Just Occurred',
        'FEDERAL OFFENSES WITH MONEY',
        'ABORTION/ILLEGAL',
        'DISORDERLY CONDUCT',
        'Rape Now',
        'BRIBERY',
        'Attempt Homicde',
        'Armed Robbery/Auto Theft In Progress',
        'Homicide'
    ]